class PartidoPolitico {
  final String id;
  final String nombre;
  final String nombreCorto;
  final String logoPath;
  final String color;

  PartidoPolitico({
    required this.id,
    required this.nombre,
    required this.nombreCorto,
    required this.logoPath,
    required this.color,
  });

  // Lista de partidos políticos inscritos en el ROP
  static List<PartidoPolitico> getPartidos() {
    return [
      PartidoPolitico(
        id: 'accion_popular',
        nombre: 'Acción Popular',
        nombreCorto: 'AP',
        logoPath: 'assets/images/partidos/accion_popular.png',
        color: '#E53935',
      ),
      PartidoPolitico(
        id: 'fuerza_popular',
        nombre: 'Fuerza Popular',
        nombreCorto: 'FP',
        logoPath: 'assets/images/partidos/fuerza_popular.png',
        color: '#FF6F00',
      ),
      PartidoPolitico(
        id: 'pte_peru',
        nombre: 'Partido de los Trabajadores y Emprendedores PTE-Perú',
        nombreCorto: 'PTE',
        logoPath: 'assets/images/partidos/pte_peru.png',
        color: '#2E7D32',
      ),
      PartidoPolitico(
        id: 'partido_morado',
        nombre: 'Partido Morado',
        nombreCorto: 'PM',
        logoPath: 'assets/images/partidos/partido_morado.png',
        color: '#7C4DFF',
      ),
      PartidoPolitico(
        id: 'peru_accion',
        nombre: 'Partido Político Perú Acción',
        nombreCorto: 'PPA',
        logoPath: 'assets/images/partidos/peru_accion.png',
        color: '#1976D2',
      ),
      PartidoPolitico(
        id: 'peru_moderno',
        nombre: 'Perú Moderno',
        nombreCorto: 'PM',
        logoPath: 'assets/images/partidos/peru_moderno.png',
        color: '#E91E63',
      ),
      PartidoPolitico(
        id: 'ahora_nacion',
        nombre: 'Ahora Nación - AN',
        nombreCorto: 'AN',
        logoPath: 'assets/images/partidos/ahora_nacion.png',
        color: '#D32F2F',
      ),
      PartidoPolitico(
        id: 'juntos_peru',
        nombre: 'Juntos por el Perú',
        nombreCorto: 'JP',
        logoPath: 'assets/images/partidos/juntos_peru.png',
        color: '#C62828',
      ),
      PartidoPolitico(
        id: 'buen_gobierno',
        nombre: 'Partido del Buen Gobierno',
        nombreCorto: 'PBG',
        logoPath: 'assets/images/partidos/buen_gobierno.png',
        color: '#F57C00',
      ),
      PartidoPolitico(
        id: 'pais_todos',
        nombre: 'Partido País para Todos',
        nombreCorto: 'PPT',
        logoPath: 'assets/images/partidos/pais_todos.png',
        color: '#FBC02D',
      ),
      PartidoPolitico(
        id: 'peru_primero',
        nombre: 'Partido Político Perú Primero',
        nombreCorto: 'PPP',
        logoPath: 'assets/images/partidos/peru_primero.png',
        color: '#D32F2F',
      ),
      PartidoPolitico(
        id: 'podemos_peru',
        nombre: 'Podemos Perú',
        nombreCorto: 'PP',
        logoPath: 'assets/images/partidos/podemos_peru.png',
        color: '#6A1B9A',
      ),
      PartidoPolitico(
        id: 'alianza_progreso',
        nombre: 'Alianza para el Progreso',
        nombreCorto: 'APP',
        logoPath: 'assets/images/partidos/alianza_progreso.png',
        color: '#1565C0',
      ),
      PartidoPolitico(
        id: 'libertad_popular',
        nombre: 'Libertad Popular',
        nombreCorto: 'LP',
        logoPath: 'assets/images/partidos/libertad_popular.png',
        color: '#FFD600',
      ),
      PartidoPolitico(
        id: 'democrata_unido',
        nombre: 'Partido Demócrata Unido Perú',
        nombreCorto: 'PDUP',
        logoPath: 'assets/images/partidos/democrata_unido.png',
        color: '#4CAF50',
      ),
      PartidoPolitico(
        id: 'patriotico_peru',
        nombre: 'Partido Patriótico del Perú',
        nombreCorto: 'PPP',
        logoPath: 'assets/images/partidos/patriotico_peru.png',
        color: '#000000',
      ),
      PartidoPolitico(
        id: 'peruanos_unidos',
        nombre: 'Partido Político Peruanos Unidos: ¡Somos Libres!',
        nombreCorto: 'PPPU',
        logoPath: 'assets/images/partidos/peruanos_unidos.png',
        color: '#9C27B0',
      ),
      PartidoPolitico(
        id: 'primero_gente',
        nombre: 'Primero la Gente - Comunidad, Ecología, Libertad y Progreso',
        nombreCorto: 'PLG',
        logoPath: 'assets/images/partidos/primero_gente.png',
        color: '#00BCD4',
      ),
      PartidoPolitico(
        id: 'avanza_pais',
        nombre: 'Avanza País - Partido de Integración Social',
        nombreCorto: 'AP',
        logoPath: 'assets/images/partidos/avanza_pais.png',
        color: '#0277BD',
      ),
      PartidoPolitico(
        id: 'nuevo_peru',
        nombre: 'Nuevo Perú por el Buen Vivir',
        nombreCorto: 'NP',
        logoPath: 'assets/images/partidos/nuevo_peru.png',
        color: '#D32F2F',
      ),
      PartidoPolitico(
        id: 'democrata_verde',
        nombre: 'Partido Demócrata Verde',
        nombreCorto: 'PDV',
        logoPath: 'assets/images/partidos/democrata_verde.png',
        color: '#4CAF50',
      ),
      PartidoPolitico(
        id: 'cooperacion_popular',
        nombre: 'Partido Político Cooperación Popular',
        nombreCorto: 'PCP',
        logoPath: 'assets/images/partidos/cooperacion_popular.png',
        color: '#FF5722',
      ),
      PartidoPolitico(
        id: 'voces_pueblo',
        nombre: 'Partido Político Popular Voces del Pueblo',
        nombreCorto: 'PPVP',
        logoPath: 'assets/images/partidos/voces_pueblo.png',
        color: '#E91E63',
      ),
      PartidoPolitico(
        id: 'progresemos',
        nombre: 'Progresemos',
        nombreCorto: 'PRO',
        logoPath: 'assets/images/partidos/progresemos.png',
        color: '#8BC34A',
      ),
      PartidoPolitico(
        id: 'batalla_peru',
        nombre: 'Batalla Perú',
        nombreCorto: 'BP',
        logoPath: 'assets/images/partidos/batalla_peru.png',
        color: '#1565C0',
      ),
      PartidoPolitico(
        id: 'aprista',
        nombre: 'Partido Aprista Peruano',
        nombreCorto: 'PAP',
        logoPath: 'assets/images/partidos/aprista.png',
        color: '#D32F2F',
      ),
      PartidoPolitico(
        id: 'democratico_federal',
        nombre: 'Partido Democrático Federal',
        nombreCorto: 'PDF',
        logoPath: 'assets/images/partidos/democratico_federal.png',
        color: '#4CAF50',
      ),
      PartidoPolitico(
        id: 'fuerza_moderna',
        nombre: 'Partido Político Fuerza Moderna',
        nombreCorto: 'PFM',
        logoPath: 'assets/images/partidos/fuerza_moderna.png',
        color: '#00BCD4',
      ),
      PartidoPolitico(
        id: 'prin',
        nombre: 'Partido Político PRIN',
        nombreCorto: 'PRIN',
        logoPath: 'assets/images/partidos/prin.png',
        color: '#D32F2F',
      ),
      PartidoPolitico(
        id: 'renovacion_popular',
        nombre: 'Renovación Popular',
        nombreCorto: 'RP',
        logoPath: 'assets/images/partidos/renovacion_popular.png',
        color: '#00ACC1',
      ),
      PartidoPolitico(
        id: 'fe_peru',
        nombre: 'Fe en el Perú',
        nombreCorto: 'FEP',
        logoPath: 'assets/images/partidos/fe_peru.png',
        color: '#4CAF50',
      ),
      PartidoPolitico(
        id: 'ciudadanos_peru',
        nombre: 'Partido Ciudadanos por el Perú',
        nombreCorto: 'PCP',
        logoPath: 'assets/images/partidos/ciudadanos_peru.png',
        color: '#FF9800',
      ),
      PartidoPolitico(
        id: 'somos_peru',
        nombre: 'Partido Democrático Somos Perú',
        nombreCorto: 'SP',
        logoPath: 'assets/images/partidos/somos_peru.png',
        color: '#FF8F00',
      ),
      PartidoPolitico(
        id: 'integridad_democratica',
        nombre: 'Partido Político Integridad Democrática',
        nombreCorto: 'PPID',
        logoPath: 'assets/images/partidos/integridad_democratica.png',
        color: '#1976D2',
      ),
      PartidoPolitico(
        id: 'sicreo',
        nombre: 'Partido SíCreo',
        nombreCorto: 'SC',
        logoPath: 'assets/images/partidos/sicreo.png',
        color: '#D32F2F',
      ),
      PartidoPolitico(
        id: 'ppc',
        nombre: 'Partido Popular Cristiano - PPC',
        nombreCorto: 'PPC',
        logoPath: 'assets/images/partidos/ppc.png',
        color: '#4CAF50',
      ),
      PartidoPolitico(
        id: 'salvemos_peru',
        nombre: 'Salvemos al Perú',
        nombreCorto: 'SAP',
        logoPath: 'assets/images/partidos/salvemos_peru.png',
        color: '#D32F2F',
      ),
      PartidoPolitico(
        id: 'fia',
        nombre: 'Frente Popular Agrícola FIA del Perú',
        nombreCorto: 'FIA',
        logoPath: 'assets/images/partidos/fia.png',
        color: '#8BC34A',
      ),
      PartidoPolitico(
        id: 'civico_obras',
        nombre: 'Partido Cívico Obras',
        nombreCorto: 'PCO',
        logoPath: 'assets/images/partidos/civico_obras.png',
        color: '#FF5722',
      ),
      PartidoPolitico(
        id: 'esperanza_2021',
        nombre: 'Partido Frente de la Esperanza 2021',
        nombreCorto: 'PFE',
        logoPath: 'assets/images/partidos/esperanza_2021.png',
        color: '#4CAF50',
      ),
      PartidoPolitico(
        id: 'peru_libre',
        nombre: 'Partido Político Nacional Perú Libre',
        nombreCorto: 'PL',
        logoPath: 'assets/images/partidos/peru_libre.png',
        color: '#D32F2F',
      ),
      PartidoPolitico(
        id: 'unidad_paz',
        nombre: 'Partido Unidad y Paz',
        nombreCorto: 'PUP',
        logoPath: 'assets/images/partidos/unidad_paz.png',
        color: '#2196F3',
      ),
      PartidoPolitico(
        id: 'camino_diferente',
        nombre: 'Un Camino Diferente',
        nombreCorto: 'UCD',
        logoPath: 'assets/images/partidos/camino_diferente.png',
        color: '#9C27B0',
      ),
    ];
  }
}
